version: "3"
services:

  web:
    build: .
    image: jctfsqli
    ports:
      - "6386:80"
    restart: always
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: jspictf
